services:
  - type: web
    name: blog-photo-generator
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 600 --workers 1 --threads 8
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
